Action update

diff --git a/.github/workflows/linter-code-check.yml b/.github/workflows/linter-code-check.yml
--- a/.github/workflows/linter-code-check.yml
+++ b/.github/workflows/linter-code-check.yml
@@ -51,6 +51,13 @@ jobs:
         run: |
           for dir in tasks/* ; do
             echo "Checking directory: $dir"
+
+            # Skip the directory if no .py files are found
+            if ! find "$dir" -name '*.py' | grep -q .; then
+              echo "No Python files found in $dir, skipping..."
+              continue
+            fi
+
             if [ -f "$dir/environment.yml" ]; then
               echo "Setting up conda environment for $dir"
               conda env create -p "$dir/conda_env" -f "$dir/environment.yml"
@@ -67,11 +74,13 @@ jobs:
             fi
 
             echo "Running mypy in $dir"
+            set +e  # Disable exit on error
             mypy_output=$(mypy --config-file "$dir/.mypy.ini" "$dir" 2>&1)
+            mypy_exit_code=$?
+            set -e  # Re-enable exit on error
             echo "$mypy_output"
 
-            if echo "$mypy_output" | grep -q 'error:';
-            then
+            if [ $mypy_exit_code -ne 0 ]; then
               echo "Running install-types in $dir"
               install-types "$dir"
               echo "Re-running mypy in $dir"
